### ISSUE TITLE
Dark variant causes dart text on dark background in input with Firefox

### ISSUE THREAD

**Issue by ddnexus** [nana-4/materia-theme#205]
Hi @nana-4.
I got an issue with Firefox changing the style of certain search inputs in the page, reported for Equilux, that looks like a Materia issue. I tried it with a new installed FF on Ubuntu GNOME latest and the user tried it with Fedora 27 with both Equilux and Materia-dark and the problem is the same.

A couple screenshots here, so you can try the same urls and search boxes to reproduce:

![first](https://user-images.githubusercontent.com/25498335/36366211-19d2e316-151b-11e8-8029-c551d124d239.png)

![second](https://user-images.githubusercontent.com/25498335/36366238-3029713e-151b-11e8-9e0f-e1b99fe7f89e.png)

Thanks

**Comment by nana-4** [comment]
Hi, thanks for reporting the bug.

I think it's not a Materia-dark/Equilux specific problem, but the problem of the entire dark themes. I believe this occurs in Adwaita-dark too. Although This should really be fixed by upstream Firefox, I'll investigate whether there is a workaround. ;)

**Comment by ddnexus** [comment]
It looks like a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=519763
Reported fixed here (but it is not fixed at all): https://bugzilla.mozilla.org/show_bug.cgi?id=1158076

Also discussed here: https://askubuntu.com/questions/978184/firefox-57-shows-dark-boxes-with-dark-text-with-gnome-dark-themes

**Comment by ddnexus** [comment]
A solution that works in the latest FF;

add something like:

```CSS
input, textarea { color: #222; background: #eee; }
```
in the file `<your firefox profile dir>/chrome/userContent.css` (create the file if it does not exist).

**Comment by actionless** [comment]
i am always using a similar workaroung as in the last comment so i think the only thing can be done is adding this topic to FAQ

**Comment by abdulocracy** [comment]
This issue happens with all dark GTK themes, and unfortunately hasn't been fixed for more than a decade upstream.
Instead of manually editing files and such, and installing unnecessary extensions, here's a cleaner workaround:

1. Navigate to about:config in Firefox.
2. Right-click and select New > String.
3. When prompted for the name, enter `widget.content.gtk-theme-override`.
4. When prompted for the value enter the name of a _light_ GTK theme, preferably the light variant of your default GTK theme (e.g. `Materia-compact` if your default `Materia-dark-compact`).
5. Restart Firefox and voila.
