### ISSUE TITLE
Oversized onscreen keyboard on HiDPI screen

### ISSUE THREAD

**Issue by ivzave** [nana-4/materia-theme#281]
Hi, in GNOME Shell the onscreen keyboard is oversized when using Materia as shell theme. It doesn't even fit into screen as you can see in screenshot so it's unusable. My display is HiDPI and scaling is set to 200% in "Display" section of GNOME settings manager.

Keyboard is correct size when switching to default shell theme. 

- Materia version: 20180922
- GTK+ 3 version: 3.22.30
- Distribution (and version): Fedora 28
- Desktop environment (and version): GNOME Shell 3.28.3

![materia](https://user-images.githubusercontent.com/1228526/46112121-1bf3a980-c1f2-11e8-8ea7-15c26c52900c.png)
![default](https://user-images.githubusercontent.com/1228526/46112127-201fc700-c1f2-11e8-898d-cf47b56818b2.png)

**Comment by RussianNeuroMancer** [comment]
I observe same issue on Dell 7285 with  2880x1920 screen and 200% default screen scaling.

    Materia version: 20180928
    GTK+ 3 version: 3.24.1
    Distribution (and version): Ubuntu 18.10
    Desktop environment (and version): GNOME Shell 3.30.1

Screenshots: https://imgur.com/a/lRkcYiZ

**Comment by NicoVarg99** [comment]
Same issue on a 1366x768 display.
![screenshot from 2018-11-20 10-01-17](https://user-images.githubusercontent.com/15423808/48762502-74539e80-ecab-11e8-93f5-9c2c422aa980.png)

**Comment by nana-4** [comment]
Thanks for your reports!

This bug has been fixed thanks to @NicoVarg99's insight :)

**Comment by RussianNeuroMancer** [comment]
Thank you for fixing this! :)

**Comment by ivzave** [comment]
![2018-11-30 00-35-52](https://user-images.githubusercontent.com/1228526/49253858-afd33300-f438-11e8-9c7e-94106556ec3a.png)
It wasn't fixed for me, however I can see more of keyboard now than before.

I've found that reducing `font-size` in same css block to `1.5em` instead of `2em` fixes it. Can't check how is works on other devices which have other screen resolution.

**Comment by nana-4** [comment]
@ivzave Oops, you're right. I didn't carefully test the fix commit (because that problem didn't occur on my 1920x1080 screen)...

Thanks for letting me know!

**Comment by RussianNeuroMancer** [comment]
@nana-4 unfortunately, HD and FullHD screen not properly supported even by Adwaita theme: https://gitlab.gnome.org/GNOME/gnome-shell/issues/675

**Comment by nana-4** [comment]
@RussianNeuroMancer Thanks for the tip!

I've already realized that even Adwaita does not work it perfectly, but I'll try to reduce the bugs as much as Adwaita has :)

**Comment by RussianNeuroMancer** [comment]
@nana-4 please check: https://gitlab.gnome.org/GNOME/gnome-shell/commit/ace44af815f973c1343093375e20321fa4603307

**Comment by nana-4** [comment]
@RussianNeuroMancer Thanks! I'll address it shortly 🙂
