### ISSUE TITLE
Highlighted menu item color is almost indistinguishable in synapse

### ISSUE THREAD

**Issue by xguse** [nana-4/materia-theme#35]
So I am not sure where to post this.  I THINK it is right to post it here because the problem showed up after I activated the theme.

I use Synapse as a launcher.  After loading Flat-plat (which ****ing rocks btw - thank you) the selected target in Synapse is colored a white color which makes it almost invisible. 

![](http://imgur.com/G31hWBX.png)

Do you have advice on how I might fix this?

Thanks!

**Comment by nana-4** [comment]
I'm really sorry for the reply late. I just fixed it for now. But if there is still any problems, please report :smiley:

**Comment by xguse** [comment]
First: thanks!

This works with the straight flat-plat theme.  But the problem still exists for the flat-plat-320/etc options.  At least for me.

**Comment by ivandotv** [comment]
I'm using flat plat - compact and this problem still exists.
Flat Plat - Dark  works okay.

**Comment by nana-4** [comment]
@ivandotv 
I couldn't reproduce the problem on Fedora 26.

![image](https://user-images.githubusercontent.com/9556384/30223957-d9caf63e-9507-11e7-9a2d-f5fb2c1fe857.png)

Would you tell me which version you are using?
- Synapse
- Distribution
- Flat-Plat

**Comment by ivandotv** [comment]
synapse  - latest
ubuntu-gnome 16.04
flat- plat  - latest
![selection_001](https://user-images.githubusercontent.com/390700/30229673-243e196e-94e3-11e7-8cdd-0be61afca885.png)

**Comment by nana-4** [comment]
@ivandotv 
Aha, Ubuntu 16.04... I got it.
I just thought that older version (gtk+ 3.18.x) would work properly...
