### ISSUE TITLE
Bad background color of text selection in Chromium with Materia-dark

### ISSUE THREAD

**Issue by AlexWayfer** [nana-4/materia-theme#455]
**Reporter Info**

- Materia version: `20191017-1`
- GTK3 version: `3.24.13`
- Distribution (and version): `Arch Linux`
- Desktop environment (and version): `GNOME 3`
- Related application (and version): `Chromium` (at least)

**Actual Issue**

Hello. Text selection background color of Materia Dark is pale and almost invisible at some websites, for example, YouTube with dark theme.

**Steps to Reproduce**

1. Set Materia Dark theme for Applications
2. Open Chromium
3. Open YouTube
4. Switch to dark theme
5. Select text

**Additional Info**

Adwaita Dark:

![image](https://user-images.githubusercontent.com/6510020/71449487-67329a00-275e-11ea-8c60-fb7dcbf384c9.png)

Materia (regular):

![image](https://user-images.githubusercontent.com/6510020/71449503-ab259f00-275e-11ea-9991-9e1111244913.png)

Materia Dark:

![image](https://user-images.githubusercontent.com/6510020/71449499-892c1c80-275e-11ea-8730-0523c3c2842c.png)

(restart of Chromium is required after theme change)

**Comment by nana-4** [comment]
Hi, thanks for the report.

Unfortunately, Chrome/Chromium doesn't read the GTK theme's selection background-color properly, if the color is translucent. This is a bug on the Chrome/Chromium side, and I don't think there is much we can do on the GTK theme side.

As a workaround, you can use the extension [chrome-scrollbar-dark.crx](https://github.com/nana-4/materia-theme/blob/master/src/chrome/chrome-scrollbar-dark.crx), which contains [a workaround](https://github.com/nana-4/materia-theme/commit/b95bb9133088672fa0278fb8d66e9052c41c46c6) for the ugly selection color in Chromium.

**Comment by AlexWayfer** [comment]
> Unfortunately, Chrome/Chromium doesn't read the GTK theme's selection background-color properly, if the color is translucent.

Can we use a less transparent and more bright color?

> This is a bug on the Chrome/Chromium side, and I don't think there is much we can do on the GTK theme side.

Do you have a link to Chromium issue about this?

> As a workaround, you can use the extension chrome-scrollbar-dark.crx, which contains a workaround for the ugly selection color in Chromium.

Thank you, I'll think about this. By the way, did you think to publish this extension to Chrome Web Store?

**Comment by AlexWayfer** [comment]
Potential fix: I've used `#8ab4f8` color from switchers in the Materia Dark theme:

![image](https://user-images.githubusercontent.com/6510020/71476097-69dfce80-27f4-11ea-80b8-966558bf51f4.png)

And it looks good:

![image](https://user-images.githubusercontent.com/6510020/71476125-972c7c80-27f4-11ea-9cdf-5ef0bd3d7aee.png)

More specific, as work-around, a custom style in Stylus extension with:

```css
::selection {
	background-color: #8ab4f8;
}
```

**Comment by nana-4** [comment]
So sorry for the delay in replying...

> Can we use a less transparent and more bright color?

Not impossible, but I don't really want to change the GTK selection color just for the Chromium bug, which is already temporarily solved with the extension.

> Do you have a link to Chromium issue about this?

No, I just encountered this bug while developing the theme.

> Thank you, I'll think about this. By the way, did you think to publish this extension to Chrome Web Store?

Yes, I did, but I won't for some reasons. Sorry but please manually install it as written in the README.

> Potential fix: I've used #8ab4f8 color from switchers in the Materia Dark theme
> And it looks good

From your screenshot, the color doesn't look `#8ab4f8`, but `#2F5A9E`. 🤔

And the biggest issue of using a bright `background-color` for the web `::selection` is most websites are bright... A bright selection color on a bright background will be almost invisible. That's why I chose the [`$primary-dark` (`#1A73E8`) based color](https://github.com/nana-4/materia-theme/blob/b95bb9133088672fa0278fb8d66e9052c41c46c6/src/_sass/chrome/_scrollbars.scss#L55) even for chrome-scrollbar-**dark**.crx...

**Comment by nana-4** [comment]
There is no reply, so closing.

**Comment by AlexWayfer** [comment]
> There is no reply, so closing.

I see no question, and the issue still here, so this is weird.
