### ISSUE TITLE
Gnome 3.36 Shell Visual Bugs

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [nana-4/materia-theme#472]
- Materia version: Latest from Git
- GTK3 version: Idk
- Distribution (and version): Ubuntu 20.04 daily 
- Desktop environment (and version): Gnome
- Related application (and version): Gnome Shell

These panel menus look really bugged out, it's driving me nuts living without Materia.
Here are some screenshots:
![Screenshot from 2020-03-16 13-55-00](https://user-images.githubusercontent.com/7698035/76765277-0e3b3680-678e-11ea-8d96-203a1f055eba.png)
![Screenshot from 2020-03-16 13-55-18](https://user-images.githubusercontent.com/7698035/76765294-13988100-678e-11ea-886e-485c0f0bd811.png)

**Comment by KUPOinyourWINDOW** [comment]
Update: The dash is also a bit wonky, there are two issues (but the one screenshot provided shows them both):
1) The text is unreadable in the search bar
2) With the dash darkening being lighter this time around, the transparent elements like the workspaces and the dock blend in more with the background and can become difficult to see.
Suggestion is to make it opaque but it's your theme and I trust your judgement <3

**Comment by Scindix** [comment]
Oddly for my notifications panel the colors are the exact opposite with Materia (default). With Materia Dark the panel appears to be completely unstyled (i.e. as in Adwaita Dark) which at least looks okayish. What flavour (Dark, Light, Compact, etc.) are you using?

Materia (default):

![Screenshot from 2020-03-17 17-22-14](https://user-images.githubusercontent.com/8752119/76877795-356c3380-6874-11ea-8011-684cadee116a.png)

Also I'd like to add that the search results don't look Materia-like: 

![Screenshot from 2020-03-17 17-23-38](https://user-images.githubusercontent.com/8752119/76878509-3f426680-6875-11ea-9a73-bb056e3a992e.png)

**Comment by sleepforlife** [comment]
same problem here

**Comment by KUPOinyourWINDOW** [comment]
> Oddly for my notifications panel the colors are the exact opposite with Materia (default). With Materia Dark the panel appears to be completely unstyled (i.e. as in Adwaita Dark) which at least looks okayish. What flavour (Dark, Light, Compact, etc.) are you using?

I'm using Materia Dark Compact as my Shell theme with Materia Light Compact as my GTK theme.

**Comment by psh-yonsei** [comment]
https://github.com/nana-4/materia-theme/issues/469#issuecomment-598782274

I believe these things was fixed recently.  Please find the above link.  In summary, you should run ./parse-sass.sh before ./install.sh (I also have an experience to miss this for the other bugfix.)

**Comment by KUPOinyourWINDOW** [comment]
I can confirm this is fixed, although the dock still blends in a little with the lighter dash shade.

**Comment by nana-4** [comment]
Sorry for the late reply.

Since this is a duplicate of #469 and I've made a new release now, I'm going to close this issue.

> I can confirm this is fixed, although the dock still blends in a little with the lighter dash shade.

Could you create a new issue for it? I'm still not sure what the issue is with that comment, so screenshots etc. would be appreciated. Thanks!
